import = [
    "~/.config/alacritty/themes/pywal.toml"
]

[cursor.style]
shape = "Underline"

[font]
size = 16.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[mouse]
hide_when_typing = true

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 15
y = 15
